// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppErrorCode = "NOT_FOUND" | "PERMISSION_DENIED" | "CLI_NOT_INSTALLED" | "PROCESS_CRASHED" | "POLICY_BLOCKED" | "PROMPT_EXPIRED" | "INVALID_INPUT" | "IO" | "NETWORK" | "INTERNAL";
