// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Famille d'une texture libre, d'après son dossier et son nom : classement dans l'onglet
 * Textures, texte envoyé au modèle, réglages de départ.
 */
export type AssetKind = "overlay" | "entity" | "armor" | "particle" | "effect" | "painting" | "gui" | "other";
