// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Version plus récente que celle en cours.
 */
export type AvailableUpdate = { version: string, title: string, 
/**
 * Notes de la release (Markdown).
 */
notes: string, 
/**
 * Page de la release sur GitHub.
 */
url: string, publishedAt: string | null, 
/**
 * Fichier qui sera téléchargé pour cette installation.
 */
asset: string, size: number, };
