// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Répartition des textures sur les faces d'un bloc (modèle parent du jeu).
 */
export type BlockLayout = "all" | "column" | "bottomTop" | "faces" | "custom";
