// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Face d'un bloc dont les faces n'ont pas toutes la même texture.
 */
export type BlockFace = "top" | "bottom" | "side" | "end" | "north" | "south" | "east" | "west";
