// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockSound } from "./BlockSound";

export type BlockRequest = { id: string, nameEn: string, nameFr: string, hardness: number, resistance: number, sound: BlockSound, };
