// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserEvent = { "type": "page", url: string, loading: boolean, } | { "type": "title", title: string, } | { "type": "download", path: string, name: string, success: boolean, image: boolean, };
