// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zone réservée par le studio, en pixels CSS de la fenêtre.
 */
export type BrowserBounds = { x: number, y: number, width: number, height: number, };
