// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueKind } from "./IssueKind";

/**
 * Erreur de build expliquée.
 */
export type BuildIssue = { kind: IssueKind, 
/**
 * Cause probable, en français.
 */
title: string, file: string | null, line: number | null, column: number | null, 
/**
 * Message d'origine (compilateur ou Gradle).
 */
message: string, 
/**
 * Solution proposée.
 */
hint: string | null, };
