// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildRecord } from "./BuildRecord";
import type { LogLevel } from "./LogLevel";
import type { LogStream } from "./LogStream";

/**
 * Flux d'une compilation, transmis par `Channel`.
 */
export type BuildEvent = { "type": "started", buildId: string, command: string, cwd: string, javaHome: string, javaVersion: string, } | { "type": "line", stream: LogStream, level: LogLevel, text: string, } | { "type": "task", name: string, } | { "type": "finished", record: BuildRecord, };
