// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildIssue } from "./BuildIssue";
import type { BuildStatus } from "./BuildStatus";
import type { BuildTask } from "./BuildTask";

/**
 * Compilation terminée, conservée dans `.mcstudio/builds.json`.
 */
export type BuildRecord = { id: string, task: BuildTask, status: BuildStatus, startedAt: string, durationMs: number, exitCode: number | null, command: string, 
/**
 * Jar produit par Gradle (`build/libs`).
 */
jar: string | null, 
/**
 * Copie du jar dans `dist/`.
 */
dist: string | null, issues: Array<BuildIssue>, 
/**
 * Phrase lisible : « Compilation réussie », « Gradle n'a pas réussi… ».
 */
summary: string, };
