// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Où l'information sur une capacité a été trouvée.
 */
export type CapabilitySource = "api" | "docs" | "user";
