// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLI officielle Higgsfield (mode compte) : présente, installable par npm.
 */
export type CliInfo = { installed: boolean, npm: boolean, package: string, page: string, };
