// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * État d'une connexion, tel que montré dans le gestionnaire de connexions.
 */
export type ConnectionState = "connected" | "disconnected" | "error" | "authRequired" | "apiKeyMissing" | "modelUnavailable" | "cliMissing";
