// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fichiers écrits par un générateur (chemins relatifs au projet).
 */
export type ContentResult = { created: Array<string>, modified: Array<string>, };
