// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { License } from "./License";
import type { ResolvedVersions } from "./ResolvedVersions";

export type CreateProjectRequest = { name: string, modId: string, package: string, mainClass: string, author: string, description: string, 
/**
 * Dossier parent ; le projet est créé dans `<parent>/<modId>`.
 */
parentDir: string, versions: ResolvedVersions, license: License, 
/**
 * Ajoute un objet, un bloc et deux recettes d'exemple.
 */
withExample: boolean, 
/**
 * JDK choisi ; `None` = détection automatique au moment du build.
 */
javaHome: string | null, };
