// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image trouvée dans le dossier Téléchargements (mode compte : site officiel, puis import).
 */
export type DownloadedImage = { path: string, name: string, modified: bigint, bytes: bigint, };
