// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origine d'un brouillon de texture.
 */
export type DraftSource = { "kind": "openRouter", model: string, prompt: string, } | { "kind": "file", name: string, };
