// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityBone } from "./EntityBone";

/**
 * Modèle d'entité : ce que le jeu construit avec `TexturedModelData` / `LayerDefinition`.
 */
export type EntityModel = { name: string, textureWidth: number, textureHeight: number, bones: Array<EntityBone>, };
