// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInfo } from "./ModelInfo";

/**
 * Ce que l'enregistrement d'un modèle d'entité a écrit.
 */
export type EntitySaved = { model: ModelInfo, 
/**
 * Classe Java générée (relative au projet).
 */
java: string | null, 
/**
 * Pourquoi le code n'a pas été généré (versions 1.14 à 1.16).
 */
note: string | null, };
