// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityCube } from "./EntityCube";

/**
 * Os d'un modèle d'entité : un point de pivot, une rotation, des cubes et des os enfants.
 */
export type EntityBone = { name: string, 
/**
 * Os parent ; `None` : à la racine du modèle.
 */
parent: string | null, 
/**
 * Pivot, relatif à celui du parent (à la racine : 24 = sol).
 */
pivot: [number, number, number], 
/**
 * Rotation en degrés autour de X, Y et Z (appliquée comme le jeu : Z, puis Y, puis X).
 */
rotation: [number, number, number], cubes: Array<EntityCube>, };
