// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cube d'un os, dans l'espace des modèles d'entité du jeu (pixels, Y vers le bas).
 */
export type EntityCube = { 
/**
 * Coin minimal, relatif au pivot de l'os.
 */
origin: [number, number, number], size: [number, number, number], 
/**
 * Coin haut-gauche de la zone du cube dans la texture (UV « en boîte » du jeu).
 */
uv: [number, number], 
/**
 * Gonflement (armure, couches superposées), sans changer la zone de texture.
 */
inflate: number, 
/**
 * Zone de texture retournée gauche-droite (bras et jambes symétriques).
 */
mirror: boolean, };
