// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaInstall } from "./JavaInstall";
import type { JdkNeed } from "./JdkNeed";

export type EnvironmentReport = { jdks: Array<JavaInstall>, needs: Array<JdkNeed>, 
/**
 * Dossier des JDK installés par Mod Studio.
 */
managedDir: string, };
