// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Archive des sources d'un projet, prête à partager ou à sauvegarder.
 */
export type ExportOutcome = { path: string, files: number, bytes: number, 
/**
 * Points à vérifier avant de partager (jeton possible dans un fichier…).
 */
warnings: Array<string>, };
