// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileDiff = { 
/**
 * Version enregistrée (`HEAD`) ; `None` : fichier nouveau.
 */
before: string | null, 
/**
 * Version sur le disque ; `None` : fichier supprimé.
 */
after: string | null, 
/**
 * Fichier binaire ou trop gros : pas de comparaison ligne à ligne.
 */
binary: boolean, };
