// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAutonomy } from "./GameAutonomy";
import type { GameBudget } from "./GameBudget";
import type { GameDimension } from "./GameDimension";
import type { GameEngine } from "./GameEngine";
import type { GameMode } from "./GameMode";
import type { GamePlatform } from "./GamePlatform";
import type { GameStyleGuide } from "./GameStyleGuide";

/**
 * Identité et réglages d'un projet (`<projet>/.gamestudio/project.json`).
 */
export type GameProject = { id: string, name: string, 
/**
 * Dossier du projet (chemin absolu).
 */
root: string, engine: GameEngine | null, 
/**
 * Version du moteur visée par le projet.
 */
engineVersion: string | null, mode: GameMode, autonomy: GameAutonomy, 
/**
 * Idée de départ, telle que la personne l'a écrite.
 */
idea: string, 
/**
 * Genres descriptifs (jamais une contrainte d'architecture, §2).
 */
genres: Array<string>, dimension: GameDimension, targets: Array<GamePlatform>, budget: GameBudget, style: GameStyleGuide, 
/**
 * Version du jeu (`0.1`, `0.2`…), avancée à chaque étape marquante.
 */
version: string, createdAt: string, updatedAt: string, };
