// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Niveau d'ambition du projet (§49 : prototype → production, ou projet existant).
 */
export type GameMode = "prototype" | "standard" | "advanced" | "production" | "existing";
