// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameModelFormat } from "./GameModelFormat";

/**
 * Travail sur les ressources confié à Blender ou au moteur (suivi comme une action moteur).
 */
export type GameAssetJob = { "kind": "blenderInspect", asset: string, } | { "kind": "blenderExport", asset: string, format: GameModelFormat | null, } | { "kind": "blenderScript", script: string, blend: string | null, } | { "kind": "engineImport" };
