// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameIssueSeverity } from "./GameIssueSeverity";

export type GameRisk = { severity: GameIssueSeverity, title: string, detail: string, };
