// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAssetKind } from "./GameAssetKind";
import type { ProviderId } from "./ProviderId";

/**
 * Demande d'image générée pour le jeu.
 */
export type GameImageRequest = { provider: ProviderId, model: string, 
/**
 * Ce que la personne demande (la consigne envoyée y ajoute l'usage et la charte).
 */
prompt: string, name: string, kind: GameAssetKind, 
/**
 * Nouvelle version d'une ressource existante.
 */
asset: string | null, aspectRatio: string | null, resolution: string | null, seed: number | null, negativePrompt: string | null, transparent: boolean, 
/**
 * Ajouter la charte graphique du projet à la consigne.
 */
useStyle: boolean, };
