// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAutonomy } from "./GameAutonomy";
import type { GameBudget } from "./GameBudget";
import type { GameDimension } from "./GameDimension";
import type { GameEngine } from "./GameEngine";
import type { GameMode } from "./GameMode";
import type { GamePlatform } from "./GamePlatform";
import type { GameStyleGuide } from "./GameStyleGuide";

/**
 * Réglages modifiables d'un projet (champs absents : inchangés).
 */
export type GameProjectPatch = { name?: string | null, engine?: GameEngine | null, engineVersion?: string | null, mode?: GameMode | null, autonomy?: GameAutonomy | null, idea?: string | null, genres?: Array<string> | null, dimension?: GameDimension | null, targets?: Array<GamePlatform> | null, budget?: GameBudget | null, style?: GameStyleGuide | null, version?: string | null, };
