// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAsset } from "./GameAsset";
import type { GameAssumptionStatus } from "./GameAssumptionStatus";
import type { GameChange } from "./GameChange";
import type { GameIssueSeverity } from "./GameIssueSeverity";
import type { GameNetworkPlan } from "./GameNetworkPlan";
import type { GamePhase } from "./GamePhase";
import type { GameSystem } from "./GameSystem";
import type { GameSystemStatus } from "./GameSystemStatus";
import type { GameTask } from "./GameTask";
import type { GameTaskStatus } from "./GameTaskStatus";
import type { GameWorldPlan } from "./GameWorldPlan";

/**
 * Une modification du graphe de connaissance, faite par la personne ou par un agent.
 */
export type GameGraphOp = { "op": "upsertSystem", system: GameSystem, } | { "op": "addCatalogSystem", id: string, } | { "op": "removeSystem", id: string, } | { "op": "setSystemStatus", id: string, status: GameSystemStatus, } | { "op": "linkFiles", id: string, files: Array<string>, } | { "op": "addDecision", title: string, decision: string, reason: string, alternatives: Array<string>, tradeoffs: string | null, } | { "op": "removeDecision", id: string, } | { "op": "addAssumption", topic: string, value: string, reason: string, } | { "op": "setAssumption", id: string, value: string | null, status: GameAssumptionStatus, } | { "op": "upsertTask", task: GameTask, } | { "op": "setTaskStatus", id: string, status: GameTaskStatus, result: string | null, conversationId: string | null, } | { "op": "removeTask", id: string, } | { "op": "addIssue", title: string, detail: string, severity: GameIssueSeverity, systems: Array<string>, source?: string, } | { "op": "setIssueOpen", id: string, open: boolean, } | { "op": "addChange", change: GameChange, } | { "op": "addVersion", version: string, label: string, summary: string, checkpoint: string | null, } | { "op": "upsertPhase", phase: GamePhase, } | { "op": "removePhase", id: string, } | { "op": "setWorld", world: GameWorldPlan, } | { "op": "setNetwork", network: GameNetworkPlan, } | { "op": "upsertAsset", asset: GameAsset, } | { "op": "removeAsset", id: string, };
