// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameIssueSeverity } from "./GameIssueSeverity";

/**
 * Erreur ou avertissement lu dans la sortie d'un outil (§107).
 */
export type GameDiagnostic = { severity: GameIssueSeverity, message: string, 
/**
 * Fichier relatif au projet quand il est connu.
 */
file: string | null, line: number | null, column: number | null, 
/**
 * Code de l'outil (`CS0246`, `C2065`…).
 */
code: string | null, 
/**
 * Outil qui l'a produit (`GDScript`, `C#`, `C++`, `Unreal`, `Blender`…).
 */
source: string, 
/**
 * Cause probable, en clair.
 */
likelyCause: string | null, 
/**
 * Piste de correction.
 */
suggestion: string | null, 
/**
 * Systèmes du graphe concernés (d'après les fichiers rattachés).
 */
systems: Array<string>, };
