// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAssetKind } from "./GameAssetKind";

/**
 * Fichier de ressource présent dans le projet mais absent du registre.
 */
export type GameLooseFile = { path: string, kind: GameAssetKind, bytes: number, inEngine: boolean, };
