// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serveur ajouté dans Game Studio.
 */
export type GameMcpOwnServer = { name: string, command: string | null, args: Array<string>, url: string | null, };
