// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trace d'une modification importante (§43 : quoi, pourquoi, impact, fichiers, risques).
 */
export type GameChange = { id: string, title: string, what: string, why: string, impact: string, files: Array<string>, systems: Array<string>, risks: Array<string>, 
/**
 * Point de restauration pris avant la modification.
 */
checkpoint: string | null, by: string, at: string, };
