// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameMcpState } from "./GameMcpState";
import type { GameMcpTool } from "./GameMcpTool";

/**
 * Résultat du dernier test d'un serveur.
 */
export type GameMcpHealth = { state: GameMcpState, message: string, server: string | null, version: string | null, tools: Array<GameMcpTool>, checkedAt: string, };
