// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAssetKind } from "./GameAssetKind";
import type { GameAssetSource } from "./GameAssetSource";
import type { GameAssetStatus } from "./GameAssetStatus";
import type { GameGeneration } from "./GameGeneration";

/**
 * Entrée du registre d'assets (§40).
 */
export type GameAsset = { id: string, name: string, kind: GameAssetKind, source: GameAssetSource, 
/**
 * Fichier relatif au projet (absent pour un concept pas encore produit).
 */
path: string | null, version: number, dependencies: Array<string>, 
/**
 * Réglages d'import pour le moteur (« échelle 0,01, axe Z en haut »).
 */
importSettings: string | null, 
/**
 * Générations successives, la plus récente en dernier.
 */
generations: Array<GameGeneration>, 
/**
 * Systèmes ou scènes qui l'utilisent.
 */
usage: Array<string>, status: GameAssetStatus, notes: string | null, updatedAt: string, };
