// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameBuildStatus } from "./GameBuildStatus";
import type { GameDimension } from "./GameDimension";
import type { GameEngine } from "./GameEngine";
import type { GameMode } from "./GameMode";

/**
 * Ligne de la liste des projets.
 */
export type GameProjectSummary = { id: string, name: string, root: string, engine: GameEngine | null, engineVersion: string | null, mode: GameMode | null, dimension: GameDimension | null, 
/**
 * Le dossier existe et contient `.gamestudio/project.json`.
 */
available: boolean, systems: number, openTasks: number, lastBuild: GameBuildStatus | null, updatedAt: string | null, lastOpened: string | null, };
