// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spécialité d'un agent (§50).
 */
export type GameAgentRole = "director" | "gameDesign" | "architecture" | "programming" | "world" | "aiNpc" | "modeling" | "texture" | "animation" | "vfx" | "uiUx" | "audio" | "network" | "backend" | "build" | "qa" | "debug" | "optimization";
