// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAction } from "./GameAction";
import type { GameBuildStatus } from "./GameBuildStatus";
import type { GameDiagnostic } from "./GameDiagnostic";
import type { GamePlatform } from "./GamePlatform";

/**
 * Exécution terminée d'une action moteur (`.gamestudio/builds/history.json`).
 */
export type GameBuildRecord = { id: string, action: GameAction, platform: GamePlatform | null, development: boolean, status: GameBuildStatus, startedAt: string, durationMs: number, exitCode: number | null, command: string, 
/**
 * Fichier ou dossier produit.
 */
output: string | null, summary: string, diagnostics: Array<GameDiagnostic>, logLines: number, };
