// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameMcpHealth } from "./GameMcpHealth";
import type { GameMcpSource } from "./GameMcpSource";
import type { GameMcpTransport } from "./GameMcpTransport";

/**
 * Serveur MCP connu, sans aucun secret.
 */
export type GameMcpServer = { 
/**
 * `source:nom`, stable.
 */
key: string, name: string, source: GameMcpSource, transport: GameMcpTransport, command: string | null, 
/**
 * Arguments, secrets masqués.
 */
args: Array<string>, 
/**
 * Adresse, paramètres masqués.
 */
url: string | null, 
/**
 * Noms des variables d'environnement et des en-têtes (jamais leurs valeurs).
 */
envKeys: Array<string>, headerKeys: Array<string>, 
/**
 * Outil piloté, deviné du nom et de la commande (`godot`, `unity`, `unreal`, `blender`).
 */
target: string | null, 
/**
 * Fichier de configuration d'où il vient.
 */
origin: string, 
/**
 * Agents qui le reçoivent.
 */
agents: Array<string>, 
/**
 * Ajouté dans Game Studio (on peut le retirer ici).
 */
removable: boolean, health: GameMcpHealth | null, };
