// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameFileKind } from "./GameFileKind";

export type GameKindStat = { kind: GameFileKind, files: number, bytes: number, };
