// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameCheckpoint = { id: string, label: string, commit: string, at: string, 
/**
 * « vous », « agent:programming », « automatique »…
 */
by: string, 
/**
 * Fichiers différents du point précédent (indicatif).
 */
files: number, };
