// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameEngine } from "./GameEngine";

/**
 * Installation d'un moteur trouvée sur la machine.
 */
export type GameEngineInstall = { engine: GameEngine, 
/**
 * Version lue sur l'installation (`4.3.stable`, `6000.0.23f1`, `5.4.4`).
 */
version: string | null, 
/**
 * Exécutable de l'éditeur.
 */
editor: string, 
/**
 * Variante console quand elle existe (Godot `_console.exe`, Unreal `-Cmd.exe`) : sortie lisible.
 */
console: string | null, 
/**
 * Dossier racine de l'installation.
 */
root: string, 
/**
 * Où elle a été trouvée : « Chemin choisi », « Unity Hub », « Epic Games Launcher », « PATH »…
 */
source: string, };
