// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Question posée seulement quand la réponse change l'architecture (§54).
 */
export type GameQuestion = { topic: string, question: string, why: string, options: Array<string>, };
