// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Étape marquante du jeu (§56 : 0.1 prototype, 0.2 inventaire…).
 */
export type GameVersion = { version: string, label: string, summary: string, checkpoint: string | null, at: string, };
