// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameLogCategory } from "./GameLogCategory";
import type { GameLogLevel } from "./GameLogLevel";

export type GameLogEntry = { at: string, category: GameLogCategory, level: GameLogLevel, message: string, detail: string | null, };
