// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameIssueSeverity } from "./GameIssueSeverity";

/**
 * Problème connu du projet.
 */
export type GameIssue = { id: string, title: string, detail: string, severity: GameIssueSeverity, systems: Array<string>, open: boolean, at: string, 
/**
 * Origine : `run:check`, `run:build`… (refermé quand la même action réussit).
 */
source: string | null, };
