// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameMcpSource = "claudeCode" | "project" | "claudeDesktop" | "cursor" | "codex" | "gemini" | "antigravity" | "gameStudio";
