// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Où vit l'état d'un système en multijoueur (§33).
 */
export type GameNetMode = "local" | "serverAuthority" | "replicated" | "predicted" | "clientOnly";
