// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAssumption } from "./GameAssumption";
import type { GameDecision } from "./GameDecision";
import type { GameDetectedSystem } from "./GameDetectedSystem";
import type { GameDimension } from "./GameDimension";
import type { GameEngineScore } from "./GameEngineScore";
import type { GameMode } from "./GameMode";
import type { GameNetworkPlan } from "./GameNetworkPlan";
import type { GamePhase } from "./GamePhase";
import type { GamePlatform } from "./GamePlatform";
import type { GameQuestion } from "./GameQuestion";
import type { GameWorldPlan } from "./GameWorldPlan";

/**
 * Spécification technique tirée d'une idée (§4).
 */
export type GameAnalysis = { idea: string, name: string, genres: Array<string>, dimension: GameDimension, perspective: string, systems: Array<GameDetectedSystem>, world: GameWorldPlan, network: GameNetworkPlan, assumptions: Array<GameAssumption>, decisions: Array<GameDecision>, engines: Array<GameEngineScore>, mode: GameMode, roadmap: Array<GamePhase>, content: Array<string>, risks: Array<string>, questions: Array<GameQuestion>, targets: Array<GamePlatform>, };
