// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Moyen par lequel une opération est réellement faite.
 */
export type GameCapabilityVia = "cli" | "files" | "mcp" | "manual";
