// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameBlendAction } from "./GameBlendAction";
import type { GameBlendImage } from "./GameBlendImage";
import type { GameBlendObject } from "./GameBlendObject";

/**
 * Résumé d'un fichier .blend lu par Blender.
 */
export type GameBlendInfo = { blender: string, file: string, unitSystem: string, unitScale: number, frameStart: number, frameEnd: number, fps: number, objects: Array<GameBlendObject>, materials: Array<string>, images: Array<GameBlendImage>, actions: Array<GameBlendAction>, 
/**
 * Triangles de tous les maillages (modificateurs appliqués).
 */
triangles: number, 
/**
 * Ce qui posera problème dans le moteur.
 */
warnings: Array<string>, readAt: string, };
