// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameNetMode } from "./GameNetMode";
import type { GameSystemCategory } from "./GameSystemCategory";
import type { GameSystemOrigin } from "./GameSystemOrigin";
import type { GameSystemStatus } from "./GameSystemStatus";

/**
 * Un système du jeu et ses liens (§6).
 */
export type GameSystem = { 
/**
 * Identifiant stable en `snake_case` (`combat_melee`).
 */
id: string, name: string, category: GameSystemCategory, 
/**
 * Rôle dans le jeu, en une ou deux phrases.
 */
role: string, origin: GameSystemOrigin, dependencies: Array<string>, 
/**
 * Événements émis (`DamageDealt`, `ItemCrafted`…).
 */
produces: Array<string>, 
/**
 * Fichiers ou motifs (`Scripts/Combat/**`), relatifs au projet.
 */
files: Array<string>, 
/**
 * Identifiants d'assets du registre.
 */
assets: Array<string>, 
/**
 * Interfaces publiques (`IDamageable`, `take_damage(amount)`).
 */
interfaces: Array<string>, 
/**
 * Types de données pilotant le système (`WeaponData`).
 */
data: Array<string>, constraints: Array<string>, 
/**
 * Vérifications attendues (« Un coup retire des points de vie »).
 */
tests: Array<string>, status: GameSystemStatus, network: GameNetMode, 
/**
 * Risque d'échelle signalé (« sans risque en prototype, risqué en production »).
 */
risk: string | null, notes: string | null, };
