// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAssumptionStatus } from "./GameAssumptionStatus";

/**
 * Hypothèse prise automatiquement (§55).
 */
export type GameAssumption = { id: string, 
/**
 * Sujet (`camera`, `players`, `engine`…).
 */
topic: string, value: string, reason: string, status: GameAssumptionStatus, at: string, };
