// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GamePhaseStatus } from "./GamePhaseStatus";

/**
 * Phase de la feuille de route (§58).
 */
export type GamePhase = { id: string, title: string, goals: Array<string>, systems: Array<string>, status: GamePhaseStatus, };
