// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Guide de style du projet (§90) : les agents le respectent pour chaque nouvel élément.
 */
export type GameStyleGuide = { visualStyle: string, palette: Array<string>, materials: string, typography: string, uiStyle: string, characterStyle: string, environmentStyle: string, vfxStyle: string, audioStyle: string, 
/**
 * Images ou pages de référence (chemins du projet ou adresses).
 */
references: Array<string>, };
