// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameNetTopology } from "./GameNetTopology";

/**
 * Plan réseau (§32 à §34).
 */
export type GameNetworkPlan = { topology: GameNetTopology, maxPlayers: number | null, reason: string, 
/**
 * Mécanismes nécessaires (lobby, matchmaking, prédiction, compensation de latence…).
 */
features: Array<string>, 
/**
 * Estimations et risques (bande passante, fréquence de mise à jour, triche).
 */
notes: Array<string>, };
