// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameCheck } from "./GameCheck";
import type { GameToolCategory } from "./GameToolCategory";
import type { GameToolState } from "./GameToolState";

/**
 * Outil de la machine et son état (§63, §111).
 */
export type GameTool = { id: string, label: string, category: GameToolCategory, state: GameToolState, version: string | null, path: string | null, 
/**
 * Ce que l'outil permet dans Game Studio.
 */
purpose: string, 
/**
 * Ce qui a été vérifié pour arriver à cet état.
 */
checks: Array<GameCheck>, 
/**
 * Étapes simples pour l'installer ou le réparer (§122).
 */
setup: Array<string>, url: string | null, 
/**
 * La personne peut désigner l'exécutable à la main.
 */
overridable: boolean, };
