// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trace d'une génération par IA (§11) : de quoi la refaire ou la modifier.
 */
export type GameGeneration = { provider: string, model: string, prompt: string, 
/**
 * Paramètres envoyés (format, taille, style…).
 */
params: Record<string, unknown>, seed: string | null, at: string, 
/**
 * Fichier produit, relatif au projet.
 */
output: string, };
