// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameFolderStat } from "./GameFolderStat";
import type { GameFoundSystem } from "./GameFoundSystem";
import type { GameKindStat } from "./GameKindStat";
import type { GameLanguageStat } from "./GameLanguageStat";
import type { GameRisk } from "./GameRisk";

/**
 * Carte d'un projet (`.gamestudio/cache/map.json`).
 */
export type GameProjectMap = { scannedAt: string, durationMs: number, files: number, bytes: number, 
/**
 * Fichiers nouveaux ou modifiés depuis l'analyse précédente.
 */
changed: number, 
/**
 * L'analyse s'est arrêtée avant la fin (trop de fichiers).
 */
truncated: boolean, kinds: Array<GameKindStat>, languages: Array<GameLanguageStat>, folders: Array<GameFolderStat>, systems: Array<GameFoundSystem>, risks: Array<GameRisk>, };
