// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Catégories du journal structuré (§78).
 */
export type GameLogCategory = "SYSTEM" | "BUILD" | "ENGINE" | "MCP" | "AI" | "NETWORK" | "ASSET" | "CODE" | "TEST" | "ERROR" | "PERFORMANCE";
