// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que l'adaptateur du moteur lit dans le projet.
 */
export type GameEngineInfo = { name: string, engineVersion: string | null, mainScene: string | null, languages: Array<string>, packages: Array<string>, };
