// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameFileChangeKind } from "./GameFileChangeKind";

export type GameFileChange = { path: string, kind: GameFileChangeKind, };
