// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameAssetKind = "model" | "texture" | "material" | "sprite" | "animation" | "audio" | "music" | "scene" | "prefab" | "script" | "shader" | "ui" | "font" | "data" | "concept" | "vfx" | "other";
