// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D'où vient un système du graphe.
 */
export type GameSystemOrigin = "catalog" | "custom" | "detected";
