// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameEngineInstall } from "./GameEngineInstall";
import type { GameTool } from "./GameTool";

/**
 * Rapport d'environnement (§63).
 */
export type GameEnvironment = { tools: Array<GameTool>, engines: Array<GameEngineInstall>, checkedAt: string, os: string, };
