// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAsset } from "./GameAsset";

/**
 * Une ressource du registre, avec ce que le disque et le moteur en disent.
 */
export type GameAssetEntry = { asset: GameAsset, 
/**
 * Le fichier existe dans le projet.
 */
exists: boolean, bytes: number, 
/**
 * Le moteur l'a pris en compte (fichier d'import présent).
 */
inEngine: boolean, 
/**
 * Chemin absolu, pour l'aperçu.
 */
absolute: string | null, };
