// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSystemCategory } from "./GameSystemCategory";

/**
 * Système du catalogue repéré dans le code.
 */
export type GameFoundSystem = { id: string, name: string, category: GameSystemCategory, 
/**
 * Déjà dans le graphe du projet.
 */
inGraph: boolean, 
/**
 * Fichiers où il apparaît (les premiers).
 */
files: Array<string>, fileCount: number, 
/**
 * Mots qui l'ont fait reconnaître.
 */
evidence: Array<string>, };
