// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameSystemCategory = "core" | "player" | "camera" | "combat" | "ai" | "npc" | "rpg" | "items" | "crafting" | "building" | "vehicles" | "narrative" | "economy" | "world" | "generation" | "environment" | "multiplayer" | "backend" | "persistence" | "ui" | "audio" | "visual" | "gameplay" | "platform";
