// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une vérification faite pendant la détection (auto-diagnostic, §123).
 */
export type GameCheck = { label: string, ok: boolean, detail: string | null, };
