// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameCheckpoint } from "./GameCheckpoint";

/**
 * État Git du projet.
 */
export type GameVcsState = { gitAvailable: boolean, repository: boolean, branch: string | null, 
/**
 * Fichiers modifiés depuis le dernier commit de la personne.
 */
dirty: number, lfs: boolean, checkpoints: Array<GameCheckpoint>, };
