// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Format d'export d'un modèle : GLB pour Godot, FBX pour Unity et Unreal.
 */
export type GameModelFormat = "glb" | "fbx";
