// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAssetEntry } from "./GameAssetEntry";
import type { GameBlenderTool } from "./GameBlenderTool";
import type { GameLooseFile } from "./GameLooseFile";

/**
 * Vue des ressources d'un projet.
 */
export type GameAssetsView = { entries: Array<GameAssetEntry>, loose: Array<GameLooseFile>, 
/**
 * La recherche des fichiers hors registre s'est arrêtée avant la fin.
 */
looseTruncated: boolean, 
/**
 * Dossier où arrivent les fichiers importés, selon le moteur.
 */
folder: string, 
/**
 * Comment le moteur prend les ressources en compte.
 */
importHint: string, blender: GameBlenderTool | null, };
