// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aperçu des deux documents.
 */
export type GameDocuments = { gdd: string, tdd: string, };
