// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameFileKind = "script" | "scene" | "texture" | "model" | "audio" | "material" | "shader" | "animation" | "font" | "video" | "data" | "other";
