// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liberté laissée aux agents (§86).
 */
export type GameAutonomy = "manual" | "assisted" | "autonomous";
