// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSystem } from "./GameSystem";

/**
 * Système retenu par l'analyse, avec ce qui l'a fait retenir.
 */
export type GameDetectedSystem = { system: GameSystem, 
/**
 * Mots de l'idée qui l'ont déclenché.
 */
evidence: Array<string>, 
/**
 * Systèmes qui en ont besoin (ajouté comme dépendance).
 */
requiredBy: Array<string>, 
/**
 * Présent dans tout jeu jouable (boucle de jeu, entrées, interface…).
 */
foundation: boolean, };
