// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAgentRole } from "./GameAgentRole";
import type { GameTaskStatus } from "./GameTaskStatus";

/**
 * Tâche du plan (§52).
 */
export type GameTask = { id: string, title: string, description: string, status: GameTaskStatus, role: GameAgentRole, dependsOn: Array<string>, systems: Array<string>, files: Array<string>, 
/**
 * Résultat attendu.
 */
expected: string, 
/**
 * Comment vérifier que c'est fait (compilation, test, contrôle en jeu).
 */
validation: string, 
/**
 * Phase de la feuille de route.
 */
phase: string | null, 
/**
 * Conversation d'agent qui a traité la tâche.
 */
conversationId: string | null, 
/**
 * Compte rendu de l'agent ou de la personne.
 */
result: string | null, order: number, createdAt: string, updatedAt: string, };
