// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameCapability } from "./GameCapability";
import type { GameEngineInfo } from "./GameEngineInfo";
import type { GameEngineInstall } from "./GameEngineInstall";
import type { GameGraph } from "./GameGraph";
import type { GameProject } from "./GameProject";

/**
 * Projet ouvert : identité, graphe, moteur, capacités réelles.
 */
export type GameProjectState = { project: GameProject, graph: GameGraph, engineInfo: GameEngineInfo | null, install: GameEngineInstall | null, capabilities: Array<GameCapability>, };
