// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameEngine } from "./GameEngine";

/**
 * Note d'un moteur pour ce projet.
 */
export type GameEngineScore = { engine: GameEngine, score: number, reasons: Array<string>, concerns: Array<string>, installed: boolean, };
