// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAction } from "./GameAction";

/**
 * Action en cours d'un projet.
 */
export type GameRunningJob = { jobId: string, action: GameAction, startedAt: string, command: string, };
