// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAssumption } from "./GameAssumption";
import type { GameAutonomy } from "./GameAutonomy";
import type { GameDecision } from "./GameDecision";
import type { GameDimension } from "./GameDimension";
import type { GameEngine } from "./GameEngine";
import type { GameMode } from "./GameMode";
import type { GameNetworkPlan } from "./GameNetworkPlan";
import type { GamePhase } from "./GamePhase";
import type { GamePlatform } from "./GamePlatform";
import type { GameSystem } from "./GameSystem";
import type { GameWorldPlan } from "./GameWorldPlan";

/**
 * Création d'un projet à partir d'une analyse relue par la personne.
 */
export type GameCreateRequest = { name: string, 
/**
 * Dossier parent ; le projet est créé dans `<parent>/<nom-en-dossier>`.
 */
parent: string, engine: GameEngine | null, 
/**
 * Installation choisie (chemin de l'éditeur) ; sinon la plus récente.
 */
engineEditor: string | null, mode: GameMode, autonomy: GameAutonomy, idea: string, genres: Array<string>, dimension: GameDimension, targets: Array<GamePlatform>, 
/**
 * Systèmes gardés (identifiants du catalogue ou systèmes propres).
 */
systems: Array<GameSystem>, assumptions: Array<GameAssumption>, decisions: Array<GameDecision>, world: GameWorldPlan | null, network: GameNetworkPlan | null, roadmap: Array<GamePhase>, 
/**
 * Unreal : module C++ en plus des Blueprints.
 */
cpp: boolean, 
/**
 * Initialiser un dépôt Git (avec le `.gitignore` du moteur).
 */
git: boolean, };
