// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameCapabilityVia } from "./GameCapabilityVia";

/**
 * Ce qu'un adaptateur sait faire, dit honnêtement.
 */
export type GameCapability = { id: string, label: string, via: GameCapabilityVia, 
/**
 * Condition à remplir (« éditeur installé », « modèles d'export installés »…).
 */
requires: string | null, 
/**
 * Remplie sur cette machine pour ce projet (`None` : pas encore vérifiable).
 */
available: boolean | null, detail: string | null, };
