// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Moteur de jeu pris en charge par un adaptateur.
 */
export type GameEngine = "godot" | "unity" | "unreal";
