// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameBlendObject = { name: string, 
/**
 * Type Blender (`MESH`, `ARMATURE`, `EMPTY`, `LIGHT`, `CAMERA`…).
 */
type: string, parent: string | null, dimensions: Array<number>, scale: Array<number>, materials: Array<string>, modifiers: Array<string>, vertices: number, triangles: number, };
