// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAction } from "./GameAction";
import type { GameBuildRecord } from "./GameBuildRecord";
import type { GameLogLevel } from "./GameLogLevel";
import type { GameLogStream } from "./GameLogStream";

/**
 * Événements d'une action en cours, transmis par un `Channel`.
 */
export type GameJobEvent = { "kind": "started", jobId: string, action: GameAction, command: string, cwd: string, timeoutSecs: number | null, } | { "kind": "line", stream: GameLogStream, level: GameLogLevel, text: string, } | { "kind": "quiet", seconds: number, } | { "kind": "finished", record: GameBuildRecord, };
