// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameProject } from "./GameProject";

/**
 * Résultat d'une création : ce qui a été écrit, et ce qui reste à faire à la main.
 */
export type GameCreateOutcome = { project: GameProject, files: Array<string>, notes: Array<string>, };
