// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Action lancée par la ligne de commande d'un moteur.
 */
export type GameAction = "setup" | "check" | "run" | "test" | "build" | "editor" | "import" | "blender";
