// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAsset } from "./GameAsset";
import type { GameAssumption } from "./GameAssumption";
import type { GameChange } from "./GameChange";
import type { GameDecision } from "./GameDecision";
import type { GameIssue } from "./GameIssue";
import type { GameNetworkPlan } from "./GameNetworkPlan";
import type { GamePhase } from "./GamePhase";
import type { GameSystem } from "./GameSystem";
import type { GameTask } from "./GameTask";
import type { GameVersion } from "./GameVersion";
import type { GameWorldPlan } from "./GameWorldPlan";

/**
 * Graphe de connaissance du projet (`<projet>/.gamestudio/graph.json`, §5).
 */
export type GameGraph = { 
/**
 * Augmente à chaque écriture : un agent sait si sa lecture est à jour.
 */
revision: number, systems: Array<GameSystem>, assets: Array<GameAsset>, decisions: Array<GameDecision>, assumptions: Array<GameAssumption>, tasks: Array<GameTask>, issues: Array<GameIssue>, changes: Array<GameChange>, versions: Array<GameVersion>, roadmap: Array<GamePhase>, world: GameWorldPlan | null, network: GameNetworkPlan | null, };
