// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameWorldKind } from "./GameWorldKind";

/**
 * Plan du monde retenu et ses conséquences (mémoire, processeur, carte graphique, disque, réseau).
 */
export type GameWorldPlan = { kind: GameWorldKind, 
/**
 * Traits combinés (`streaming`, `procedural`, `destructible`…).
 */
traits: Array<GameWorldKind>, reason: string, 
/**
 * Points d'attention par ressource : « Mémoire : chunks déchargés au-delà de … ».
 */
concerns: Array<string>, };
