// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Architecture de monde (§14).
 */
export type GameWorldKind = "static" | "sceneBased" | "levelBased" | "openWorld" | "streaming" | "procedural" | "infinite" | "voxel" | "tile" | "destructible" | "hybrid";
