// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameBlendImage = { name: string, path: string, packed: boolean, found: boolean, size: Array<number>, };
