// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Décision d'architecture (§124).
 */
export type GameDecision = { id: string, title: string, decision: string, reason: string, alternatives: Array<string>, tradeoffs: string | null, 
/**
 * « analyse », « vous », « agent:architecture »…
 */
by: string, at: string, };
