// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Budget de performance (§73). Tout est facultatif.
 */
export type GameBudget = { targetFps: number | null, resolution: string | null, memoryMb: number | null, cpuMs: number | null, gpuMs: number | null, networkKbps: number | null, };
