// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clé Google AI Studio : présente ou non, et ce que l'API Gemini en dit quand on vérifie.
 */
export type GeminiStatus = { configured: boolean, 
/**
 * Modèles d'image accessibles avec la clé (lu lors de la vérification).
 */
imageModels: number | null, 
/**
 * Vérification impossible (réseau, clé refusée) : explication.
 */
problem: string | null, };
