// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitFile = { 
/**
 * Chemin relatif au dépôt, avec `/`.
 */
path: string, 
/**
 * `modified`, `added`, `deleted`, `renamed`, `untracked`, `conflicted`.
 */
status: string, added: number, removed: number, };
