// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpuInfo = { name: string, 
/**
 * `nvidia`, `amd`, `intel`, `apple`, `other`.
 */
vendor: string, 
/**
 * Mémoire vidéo dédiée (Mo) ; `None` si inconnue.
 */
vramMb: number | null, 
/**
 * Carte séparée (mémoire propre) plutôt que puce intégrée.
 */
dedicated: boolean, };
