// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Élément d'interface de départ, dessiné sans IA au format des écrans du jeu.
 */
export type GuiPreset = "panel" | "inventoryPanel" | "button" | "slot" | "arrow" | "blank";
