// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuiPreset } from "./GuiPreset";

export type GuiRequest = { 
/**
 * Nom du fichier dans `textures/gui/` (minuscules, chiffres, `_`).
 */
name: string, preset: GuiPreset, 
/**
 * Taille de la toile vide (`Blank`) : 1 à 256.
 */
width: number, height: number, };
