// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuInfo } from "./GpuInfo";
import type { HardwareTier } from "./HardwareTier";

export type HardwareInfo = { 
/**
 * `windows`, `macos`, `linux`.
 */
os: string, 
/**
 * `x86_64`, `aarch64`…
 */
arch: string, cpu: string, cores: number, ramMb: number, gpus: Array<GpuInfo>, tier: HardwareTier, 
/**
 * Pourquoi cette gamme (phrases courtes, affichées telles quelles).
 */
reasons: Array<string>, };
