// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gamme de la machine, pour proposer des modèles locaux raisonnables.
 */
export type HardwareTier = "low" | "mid" | "high";
