// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySource } from "./CapabilitySource";

/**
 * Un modèle (« application ») Higgsfield et les arguments qu'il reçoit.
 */
export type HiggsfieldModelSpec = { 
/**
 * Chemin de l'application (« bytedance/seedream/v4/text-to-image »).
 */
id: string, name: string, 
/**
 * Formats proposés (`aspect_ratio`) ; vide = argument non envoyé.
 */
aspectRatios: Array<string>, 
/**
 * Paliers proposés (`resolution`) ; vide = argument non envoyé.
 */
resolutions: Array<string>, 
/**
 * Envoie `seed`.
 */
seed: boolean, 
/**
 * Argument qui reçoit les images d'entrée (« image_urls »…) ; absent = texte seulement.
 */
imageField: string | null, 
/**
 * L'argument attend une liste d'adresses (sinon une seule).
 */
imageFieldList: boolean, 
/**
 * Arguments fixes ajoutés à chaque demande (objet JSON).
 */
extra: Record<string, unknown> | null, source: CapabilitySource, };
