// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outil officiel de Higgsfield (mode compte) : présent, installable par npm.
 */
export type HiggsfieldCliState = { installed: boolean, npm: boolean, package: string, };
