// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageJobStatus = "waiting" | "running" | "completed" | "failed" | "cancelled";
