// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageBackgroundAction } from "./ImageBackgroundAction";
import type { ImageInpaintMode } from "./ImageInpaintMode";
import type { ImageReferenceRole } from "./ImageReferenceRole";

/**
 * Ce qu'on demande à l'IA. Chaque opération sait quelles images envoyer et comment
 * recoller le résultat (voir `pipeline.rs`).
 */
export type ImageAiOperation = { "type": "generate", references: Array<ImageReferenceRole>, } | { "type": "edit", source: string, references: Array<ImageReferenceRole>, } | { "type": "inpaint", source: string, mask_png: string, mode: ImageInpaintMode, } | { "type": "outpaint", source: string, width: number, height: number, offset_x: number, offset_y: number, } | { "type": "variation", source: string, keep: Array<string>, } | { "type": "restyle", source: string, style: string, } | { "type": "upscale", source: string, } | { "type": "background", source: string, action: ImageBackgroundAction, } | { "type": "restore", source: string, };
