// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Consommation rapportée par le fournisseur ; `None` = non communiqué.
 */
export type ImageUsage = { costUsd: number | null, inputTokens: number | null, outputTokens: number | null, 
/**
 * Remarque lisible (« coût non communiqué par le fournisseur »…).
 */
note: string | null, };
