// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";

/**
 * Réglages communs d'une demande à l'IA. Seuls ceux que le modèle accepte sont transmis.
 */
export type ImageAiSettings = { provider: ProviderId, model: string, prompt: string, negativePrompt: string | null, aspectRatio: string | null, resolution: string | null, 
/**
 * Nombre de résultats (1…20) ; découpé en demandes si le modèle en produit moins à la fois.
 */
count: number, seed: number | null, quality: string | null, transparentBackground: boolean, };
