// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageExportFormat } from "./ImageExportFormat";

export type ImageExportRequest = { projectId: string, nodes: Array<string>, directory: string, format: ImageExportFormat, quality: number, maxSide: number | null, naming: string, 
/**
 * Fond appliqué aux zones transparentes pour les formats sans transparence (JPEG).
 */
matte: [number, number, number], };
