// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageProjectSummary = { id: string, name: string, updatedAt: number, images: number, cover: string | null, };
