// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageProject } from "./ImageProject";

/**
 * Résultat d'un traitement par lot (import, opération locale sur plusieurs versions).
 */
export type ImageBatchOutcome = { 
/**
 * Projet après le dernier ajout réussi.
 */
project: ImageProject | null, 
/**
 * Versions créées.
 */
created: Array<string>, 
/**
 * Ce qui n'a pas pu être traité, et pourquoi.
 */
skipped: Array<string>, };
