// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageModel } from "./ImageModel";

export type ImageModelList = { models: Array<ImageModel>, 
/**
 * Liste lue dans le cache : OpenRouter injoignable.
 */
offline: boolean, };
