// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageAiOperation } from "./ImageAiOperation";
import type { ImageAiSettings } from "./ImageAiSettings";
import type { ImageFailureKind } from "./ImageFailureKind";
import type { ImageJobStatus } from "./ImageJobStatus";
import type { ImageUsage } from "./ImageUsage";
import type { ProviderId } from "./ProviderId";

/**
 * Une tâche de la file (génération, édition, agrandissement…).
 */
export type ImageJob = { id: string, 
/**
 * Tâches nées d'une même demande (plusieurs résultats découpés en demandes).
 */
group: string, projectId: string, label: string, status: ImageJobStatus, provider: ProviderId, model: string, createdAt: number, startedAt: number | null, finishedAt: number | null, 
/**
 * Versions créées.
 */
results: Array<string>, error: string | null, 
/**
 * Nature de l'échec : le frontend propose l'action qui corrige (clé, crédit, modèle…).
 */
failure: ImageFailureKind | null, usage: ImageUsage | null, 
/**
 * Demande d'origine, gardée pour « Réessayer » (source et consigne ne se perdent pas).
 */
operation: ImageAiOperation, settings: ImageAiSettings, };
