// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageExportResult = { files: Array<string>, 
/**
 * Remarques (transparence aplatie en JPEG, WebP sans perte…).
 */
notes: Array<string>, };
