// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageNodeKind } from "./ImageNodeKind";
import type { ImageUsage } from "./ImageUsage";
import type { ProviderId } from "./ProviderId";

/**
 * Une version d'image du projet. Rien n'est jamais écrasé : chaque opération en ajoute une,
 * rattachée à la version dont elle part (`parent`).
 */
export type ImageNode = { id: string, parent: string | null, kind: ImageNodeKind, label: string, 
/**
 * Chemin absolu du fichier (lu par le webview via le protocole d'assets).
 */
file: string, 
/**
 * Vignette (320 px), chemin absolu.
 */
thumb: string, width: number, height: number, mime: string, createdAt: bigint, prompt: string | null, negativePrompt: string | null, provider: ProviderId | null, model: string | null, 
/**
 * Réglages utilisés (format, résolution, graine, rectangle de recadrage…).
 */
params: Record<string, unknown>, 
/**
 * Masque utilisé (blanc = zone modifiée), chemin absolu.
 */
mask: string | null, 
/**
 * Versions utilisées comme références.
 */
references: Array<string>, usage: ImageUsage | null, 
/**
 * Remarque (réglages retirés par le modèle…).
 */
note: string | null, favorite: boolean, };
