// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageReferenceRole = { node: string, 
/**
 * « personnage », « vêtements », « décor », « style »… (texte libre, peut être vide).
 */
role: string, };
