// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageNode } from "./ImageNode";

export type ImageProject = { id: string, name: string, createdAt: bigint, updatedAt: bigint, nodes: Array<ImageNode>, 
/**
 * Version affichée.
 */
current: string | null, 
/**
 * Versions épinglées comme références du panneau IA.
 */
references: Array<string>, 
/**
 * Derniers réglages du panneau IA (fournisseur, modèle, format…), rendus tels quels.
 */
aiSettings: Record<string, unknown>, };
