// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageExportFormat } from "./ImageExportFormat";

export type ImageExportPreset = { id: string, name: string, format: ImageExportFormat, 
/**
 * Qualité JPEG (1…100).
 */
quality: number, 
/**
 * Plus grand côté en pixels (réduction seulement) ; `None` = taille d'origine.
 */
maxSide: number | null, 
/**
 * Nom des fichiers : `{projet}`, `{version}`, `{n}`, `{date}`.
 */
naming: string, };
