// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qui a produit une version d'image.
 */
export type ImageNodeKind = "import" | "generate" | "edit" | "inpaint" | "outpaint" | "variation" | "restyle" | "upscale" | "background" | "restore" | "combine" | "crop" | "resize" | "rotate" | "flip" | "adjust" | "move" | "paint" | "chromaKey" | "blur";
