// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opérations faites sur la machine, sans envoi à un service.
 */
export type ImageLocalOperation = { "type": "crop", x: number, y: number, width: number, height: number, } | { "type": "resize", width: number, height: number, } | { "type": "upscale", factor: number, sharpen: boolean, } | { "type": "rotate", degrees: number, } | { "type": "flip", horizontal: boolean, } | { "type": "adjust", brightness: number, contrast: number, hue: number, } | { "type": "blur", sigma: number, mask_png: string | null, inside: boolean, } | { "type": "move", mask_png: string, dx: number, dy: number, } | { "type": "chromaKey", color: [number, number, number], tolerance: number, };
