// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service qui dessine les textures, avec la clé API de la personne.
 */
export type ImageProvider = "openRouter" | "gemini";
