// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Modèle capable de produire des images (OpenRouter ou Google Gemini).
 */
export type ImageModel = { id: string, name: string, 
/**
 * Aucun coût annoncé (prix nuls ou suffixe `:free`).
 */
free: boolean, description: string, 
/**
 * Le modèle répond aussi du texte (`modalities: ["image", "text"]`).
 */
textOutput: boolean, };
