// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiggsfieldModelSpec } from "./HiggsfieldModelSpec";
import type { ImageExportPreset } from "./ImageExportPreset";
import type { ImageFormatPreset } from "./ImageFormatPreset";

/**
 * Réglages du module, rangés dans `settings.json`.
 */
export type ImageMakerSettings = { formatPresets: Array<ImageFormatPreset>, exportPresets: Array<ImageExportPreset>, higgsfieldModels: Array<HiggsfieldModelSpec>, 
/**
 * Tâches IA lancées en même temps par fournisseur.
 */
parallelPerProvider: number, 
/**
 * Projet qui reçoit les images demandées par d'autres modules.
 */
integrationProject: string | null, };
