// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Format de toile nommé (réseau social, écran, impression…), modifiable par la personne.
 */
export type ImageFormatPreset = { id: string, name: string, width: number, height: number, };
