// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderId } from "./LoaderId";

/**
 * Ce que l'examen d'un projet existant (Fabric, Forge, NeoForge) a trouvé, avant l'import.
 */
export type ImportPreview = { path: string, 
/**
 * Déjà un projet Mod Studio : il suffit de l'ouvrir.
 */
existing: boolean, loader: LoaderId | null, minecraft: string, loaderVersion: string, mappingsVersion: string | null, apiVersion: string | null, modId: string, name: string, package: string, mainClass: string, modVersion: string, author: string, description: string, 
/**
 * Version de Gradle du wrapper du projet.
 */
gradle: string | null, 
/**
 * Profil Mod Studio qui sait construire ce projet.
 */
profileId: string | null, 
/**
 * Pourquoi le projet ne peut pas être importé.
 */
problem: string | null, 
/**
 * Remarques (mappings, paquet déduit…).
 */
notes: Array<string>, };
