// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaInstall } from "./JavaInstall";

/**
 * Déroulé d'une installation de JDK, transmis par `Channel`.
 */
export type InstallEvent = { "type": "downloading", received: number, total: number, } | { "type": "verifying" } | { "type": "extracting" } | { "type": "done", install: JavaInstall, } | { "type": "failed", message: string, };
