// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Comment cette copie d'ARCHIMED a été installée : décide du fichier à télécharger.
 */
export type InstallKind = "installer" | "portable" | "dev";
