// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueKind = "java" | "gradle" | "json" | "dependency" | "network" | "javaVersion" | "mapping" | "unknown";
