// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemRequest = { 
/**
 * Nom de registre (`ruby`).
 */
id: string, nameEn: string, nameFr: string, };
