// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaInstall } from "./JavaInstall";

/**
 * JDK retenu pour un projet, ou ce qui manque.
 */
export type JavaStatus = { install: JavaInstall | null, min: number, max: number | null, 
/**
 * Ce qu'il faut installer quand aucun JDK ne convient.
 */
problem: string | null, };
