// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JDK installé sur la machine.
 */
export type JavaInstall = { path: string, version: string, major: number, vendor: string | null, };
