// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaInstall } from "./JavaInstall";

/**
 * Besoin en Java de l'ensemble des profils : quelle version, et qui la satisfait.
 */
export type JdkNeed = { major: number, 
/**
 * Cette version exactement (Forge 1.14 – 1.20 : les JVM plus récentes échouent).
 */
exact: boolean, 
/**
 * JDK compatible déjà présent (le plus proche du besoin).
 */
installed: JavaInstall | null, 
/**
 * Plages de Minecraft concernées (« Fabric · 1.14 – 1.16.5 »…).
 */
usedBy: Array<string>, };
