// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JDK prêt à être téléchargé, tel que la source officielle le décrit.
 */
export type JdkOffer = { major: number, 
/**
 * `jdk-21.0.4+7`
 */
releaseName: string, vendor: string, url: string, fileName: string, size: number, sha256: string, 
/**
 * Dossier où il sera installé (données d'ARCHIMED, rien dans le système).
 */
targetDir: string, };
