// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * D'où vient la clé utilisée.
 */
export type KeySource = { "kind": "own" } | { "kind": "shared", module: string, };
