// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mod loader d'un projet.
 */
export type LoaderId = "fabric" | "forge" | "neoforge";
