// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderId } from "./LoaderId";

/**
 * Prise en charge d'une version de Minecraft par un loader.
 */
export type LoaderSupport = { loader: LoaderId, 
/**
 * Le loader publie une version pour ce Minecraft (métadonnées officielles).
 */
available: boolean, 
/**
 * Profil Mod Studio qui sait construire ce couple ; `None` = non supporté.
 */
profileId: string | null, 
/**
 * Pourquoi ce couple n'est pas pris en charge (quand `profile_id` est `None`).
 */
reason: string | null, };
