// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * État d'un serveur local d'IA (Ollama) ou de voix (Voicebox).
 */
export type LocalServerStatus = { running: boolean, url: string, version: string | null, models: Array<string>, };
