// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Événement du modèle local (Ollama) pendant une réponse.
 */
export type LocalChatEvent = { "type": "delta", text: string, } | { "type": "done" } | { "type": "error", message: string, };
