// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalModule } from "./LocalModule";

export type LocalStatus = { 
/**
 * Dossier du code source suivi (`None` : inconnu).
 */
sourceDir: string | null, 
/**
 * Choisi par la personne (ou `pnpm new:module`), et non celui de la compilation.
 */
configured: boolean, 
/**
 * Le dossier existe et contient le code d'ARCHIMED.
 */
valid: boolean, modules: Array<LocalModule>, 
/**
 * Délai de calme avant qu'un module soit « prêt » (ms).
 */
quietMs: number, };
