// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalModuleState } from "./LocalModuleState";

export type LocalModule = { id: string, name: string, state: LocalModuleState, 
/**
 * Dossier du module (`src/modules/<id>`).
 */
path: string, 
/**
 * Dernière modification d'un de ses fichiers (ms).
 */
modifiedAt: number, 
/**
 * Rien n'a bougé depuis `QUIET`, le manifeste est complet et le modèle a été remplacé.
 */
ready: boolean, 
/**
 * Encore le contenu du modèle de `pnpm new:module` (écran « À implémenter »…).
 */
unfinished: boolean, };
