// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Demande d'un agent (outil MCP) transmise à l'interface (événement `voice:mcp-call`).
 */
export type McpCall = { callId: string, tool: string, arguments: Record<string, unknown>, };
