// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serveur MCP d'ARCHIMED : adresse et configuration à coller dans un agent externe.
 */
export type McpInfo = { running: boolean, url: string | null, 
/**
 * Bloc `mcpServers` complet (jeton compris) pour Claude Code, Cursor…
 */
config: string | null, tools: Array<string>, 
/**
 * Appels reçus depuis le démarrage.
 */
calls: number, };
