// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilitySource } from "./CapabilitySource";

/**
 * Ce qu'un modèle sait faire. Une option absente ici n'est jamais proposée.
 */
export type ModelCapabilities = { 
/**
 * Crée une image à partir d'un texte.
 */
textToImage: boolean, 
/**
 * Accepte des images en entrée : édition par consigne, image vers image, références.
 */
imageInput: boolean, 
/**
 * Nombre d'images d'entrée accepté, quand il est connu.
 */
maxInputImages: number | null, 
/**
 * Accepte un masque natif (sinon la zone est indiquée au modèle, puis recollée ici).
 */
nativeMask: boolean, 
/**
 * Formats proposés (« 16:9 »…) ; vide = format non réglable.
 */
aspectRatios: Array<string>, 
/**
 * Paliers de résolution (« 1K », « 2K »…) ; vide = non réglable.
 */
resolutions: Array<string>, 
/**
 * Images par demande (1 = une demande par image).
 */
maxImagesPerRequest: number, seed: boolean, negativePrompt: boolean, transparentBackground: boolean, qualities: Array<string>, source: CapabilitySource, };
