// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelKind } from "./ModelKind";

/**
 * Un modèle 3D du projet.
 */
export type ModelInfo = { kind: ModelKind, 
/**
 * `block/lamp`, `item/ruby_sword` (chemin sous `models/`), nom de l'entité ou de l'armure.
 */
id: string, label: string, 
/**
 * Fichier source, relatif au projet.
 */
relative: string, 
/**
 * Bloc ou objet décrit par ses propres cubes (`elements`), et non par un parent.
 */
custom: boolean, parent: string | null, 
/**
 * Textures portées (relatives au projet) : entité ; couches 1 et 2 d'une armure.
 */
textures: Array<string>, modified: number | null, };
