// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";
import type { ProviderModel } from "./ProviderModel";

export type ModelList = { provider: ProviderId, models: Array<ProviderModel>, 
/**
 * Liste reprise du cache : le fournisseur n'a pas répondu.
 */
offline: boolean, 
/**
 * Pourquoi la liste est vide ou partielle.
 */
note: string | null, };
