// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Famille d'un modèle 3D du mod (onglet Modèles).
 */
export type ModelKind = "block" | "item" | "entity" | "armor";
