// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fichier de modèle de bloc ou d'objet, lu tel quel.
 */
export type ModelFile = { relative: string, exists: boolean, 
/**
 * Contenu JSON (vide si le fichier n'existe pas).
 */
json: string, };
