// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Résultat d'une suppression.
 */
export type ModuleRemoval = { 
/**
 * Octets partis à la Corbeille.
 */
freed: number, 
/**
 * Clés qui n'ont pas pu être effacées (le reste est fait).
 */
credentialsLeft: Array<string>, };
