// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qu'un module occupe sur la machine.
 */
export type ModuleFootprint = { 
/**
 * Taille de son dossier de données, en octets.
 */
bytes: number, files: number, 
/**
 * Il donne des outils aux agents (déclaration MCP).
 */
tools: boolean, 
/**
 * Nombre de clés qu'il peut ranger dans le Gestionnaire d'identifiants.
 */
credentials: number, };
