// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clé OpenRouter : présente ou non, et ce qu'OpenRouter en dit quand on vérifie.
 */
export type OpenRouterStatus = { configured: boolean, 
/**
 * Libellé renvoyé par OpenRouter (clé masquée ou nom donné sur le site).
 */
label: string | null, 
/**
 * Compte sans crédit acheté : seuls les modèles gratuits répondent.
 */
freeTier: boolean | null, 
/**
 * Crédit restant en dollars, quand la clé a une limite.
 */
creditsLeft: number | null, 
/**
 * Vérification impossible (réseau, clé refusée) : explication.
 */
problem: string | null, };
