// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pixels d'un brouillon, pour l'éditeur (RVBA, ligne par ligne, en base64).
 */
export type PixelData = { width: number, height: number, rgba: string, };
