// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tiling } from "./Tiling";

/**
 * Réglages de conversion en pixel-art.
 */
export type PixelOptions = { 
/**
 * Côté de la texture en pixels : 16, 32 ou 64.
 */
size: number, 
/**
 * Nombre maximal de couleurs (0 : sans limite).
 */
colors: number, 
/**
 * Retirer le fond et cadrer l'objet (objets, icône détourée).
 */
transparent: boolean, 
/**
 * Raccord quand la texture est répétée (faces de bloc).
 */
tiling: Tiling, 
/**
 * Contour sombre d'un pixel autour de l'objet, comme les objets du jeu.
 */
outline: boolean, 
/**
 * Éléments d'interface : taille libre (remplace `size`), 1 à 256 pixels.
 */
width: number | null, height: number | null, 
/**
 * Élément posé en haut à gauche d'une toile 256 × 256 (convention des écrans du jeu).
 */
atlas: boolean, };
