// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Réglages de conversion en pixel-art.
 */
export type PixelOptions = { 
/**
 * Côté de la texture en pixels : 16, 32 ou 64.
 */
size: number, 
/**
 * Nombre maximal de couleurs (0 : sans limite).
 */
colors: number, 
/**
 * Retirer le fond et cadrer l'objet (objets, icône détourée).
 */
transparent: boolean, };
