// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortStep } from "./PortStep";

/**
 * Ce qu'un portage fera, montré avant de confirmer.
 */
export type PortPlan = { fromMinecraft: string, toMinecraft: string, fromProfile: string, toProfile: string, steps: Array<PortStep>, 
/**
 * Changements d'API connus entre les deux versions.
 */
notes: Array<string>, };
