// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Étape d'un portage vers une autre version de Minecraft.
 */
export type PortStep = { title: string, detail: string, 
/**
 * Faite par Mod Studio ; sinon à faire dans le code (assistant IA).
 */
automatic: boolean, };
