// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";

/**
 * Résultat d'un portage.
 */
export type PortOutcome = { summary: ProjectSummary, 
/**
 * Point de restauration créé avant (pour annuler).
 */
snapshot: string, done: Array<string>, warnings: Array<string>, 
/**
 * Message prêt pour l'assistant IA (code Java à adapter).
 */
prompt: string, };
