// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une ligne de prix donnée par le fournisseur (jamais inventée).
 */
export type PriceLine = { 
/**
 * Ce qui est facturé (« image produite », « image d'entrée »…).
 */
label: string, costUsd: number, 
/**
 * Par quoi (« image », « mégapixel », « demande », « token »).
 */
unit: string, };
