// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderId } from "./LoaderId";

/**
 * Profil de version : ce qu'il faut pour construire un mod pour une plage de versions.
 */
export type ProfileInfo = { id: string, loader: LoaderId, label: string, minecraftMin: string, minecraftMax: string, java: number, javaMax: number | null, gradle: string, mappings: string, };
