// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectStats = { javaClasses: number, kotlinClasses: number, items: number, blocks: number, entities: number, recipes: number, lootTables: number, textures: number, models: number, sounds: number, langFiles: number, assets: number, };
