// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fichier ouvert dans l'éditeur.
 */
export type ProjectFile = { path: string, 
/**
 * Texte (vide pour un fichier binaire).
 */
content: string, binary: boolean, 
/**
 * PNG, JPEG… : aperçu au lieu du texte.
 */
image: boolean, 
/**
 * Fichier trop gros : seul le début est montré, en lecture seule.
 */
truncated: boolean, size: number, 
/**
 * Date de modification (ms) : l'enregistrement refuse d'écraser un fichier changé entre-temps.
 */
modified: number, };
