// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entrée de l'explorateur ; `path` est relatif au projet, avec des `/`.
 */
export type ProjectEntry = { name: string, path: string, isDir: boolean, size: number, 
/**
 * Dossier de build, de cache ou d'état interne : affiché en retrait.
 */
ignored: boolean, };
