// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildRecord } from "./BuildRecord";
import type { ProjectHealth } from "./ProjectHealth";
import type { ProjectMeta } from "./ProjectMeta";

/**
 * Entrée de la liste des projets.
 */
export type ProjectSummary = { id: string, path: string, health: ProjectHealth, meta: ProjectMeta | null, 
/**
 * Date de dernière modification d'un fichier source (ISO 8601).
 */
updatedAt: string | null, lastBuild: BuildRecord | null, };
