// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { License } from "./License";
import type { ResolvedVersions } from "./ResolvedVersions";

/**
 * `.mcstudio/project.json` : identité et contexte de version d'un projet.
 */
export type ProjectMeta = { format: number, id: string, name: string, modId: string, package: string, mainClass: string, author: string, description: string, modVersion: string, license: License, versions: ResolvedVersions, javaHome: string | null, createdAt: string, };
