// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageUsage } from "./ImageUsage";

/**
 * Réécriture d'une description par un modèle de texte.
 */
export type PromptSuggestion = { prompt: string, model: string, usage: ImageUsage, };
