// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextureStyle } from "./TextureStyle";

/**
 * Comment le texte envoyé au modèle est construit.
 */
export type PromptSettings = { style: TextureStyle, 
/**
 * Consignes ajoutées à la fin (« lumière froide », « bordure dorée »…).
 */
extra: string, 
/**
 * Une texture de référence accompagne la demande.
 */
withReference: boolean, 
/**
 * Taille visée (éléments d'interface), pour annoncer le format au modèle.
 */
width: number | null, height: number | null, 
/**
 * Le fond sera retiré : le modèle dessine sur un fond d'incrustation uni (magenta, ou vert
 * si l'objet est rose ou violet).
 */
transparent: boolean, };
