// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionState } from "./ConnectionState";
import type { KeySource } from "./KeySource";
import type { ProviderId } from "./ProviderId";

export type ProviderStatus = { provider: ProviderId, name: string, state: ConnectionState, keySource: KeySource | null, 
/**
 * Début et fin de la clé (« sk-or-…3f9a ») : jamais la clé entière.
 */
maskedKey: string | null, 
/**
 * Explication lisible (erreur, ce que la clé ouvre…).
 */
detail: string | null, 
/**
 * Crédit restant, quand le fournisseur le donne.
 */
credits: string | null, 
/**
 * Ce qu'il faut coller dans le champ de clé.
 */
keyHint: string, 
/**
 * Page officielle où créer une clé.
 */
keyUrl: string, };
