// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Comment on se connecte : clé d'API, ou compte de la personne (connexion dans son navigateur,
 * par l'outil officiel du fournisseur ; aucun mot de passe ne passe par l'application).
 */
export type ProviderAccess = "key" | "account";
