// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelCapabilities } from "./ModelCapabilities";
import type { PriceLine } from "./PriceLine";
import type { ProviderId } from "./ProviderId";

export type ProviderModel = { provider: ProviderId, id: string, name: string, description: string, capabilities: ModelCapabilities, 
/**
 * Prix connus ; vide = le fournisseur ne les donne pas ici.
 */
pricing: Array<PriceLine>, 
/**
 * Sans frais selon le fournisseur.
 */
free: boolean, };
