// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fournisseurs d'images branchés par API. En ajouter un : une variante ici, un fichier
 * dans `providers/`, une ligne dans `Imaging::new`.
 */
export type ProviderId = "openrouter" | "gemini" | "higgsfield" | "higgsfieldAccount";
