// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recette, au format de données de la version du projet.
 */
export type RecipeRequest = { "type": "shaped", id: string, pattern: Array<string>, 
/**
 * Symbole → objet (`minecraft:stick`, `monmod:ruby`).
 */
key: { [key in string]?: string }, result: string, count: number, } | { "type": "shapeless", id: string, ingredients: Array<string>, result: string, count: number, } | { "type": "smelting", id: string, ingredient: string, result: string, experience: number, cookingTime: number, };
