// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderId } from "./LoaderId";

/**
 * Versions exactes retenues pour créer un projet.
 */
export type ResolvedVersions = { profileId: string, loader: LoaderId, minecraft: string, loaderVersion: string, 
/**
 * Yarn pour Fabric ; `None` pour les mappings officiels.
 */
mappingsVersion: string | null, 
/**
 * Fabric API ; `None` pour Forge et NeoForge.
 */
apiVersion: string | null, java: number, javaMax: number | null, gradle: string, plugin: string, 
/**
 * Résolu depuis le cache faute de réseau.
 */
offline: boolean, };
