// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotFile } from "./SnapshotFile";
import type { SnapshotKind } from "./SnapshotKind";

/**
 * Point de restauration : copie des fichiers concernés, dans `.mcstudio/snapshots/<id>/`.
 */
export type Snapshot = { id: string, label: string, kind: SnapshotKind, createdAt: string, files: Array<SnapshotFile>, size: number, };
