// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotFile = { path: string, 
/**
 * Le fichier n'existait pas : le restaurer revient à le supprimer (Corbeille).
 */
existed: boolean, };
