// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Version compilée depuis le code source : de quoi la mettre à jour sans perdre ses modules.
 */
export type SourceBuild = { 
/**
 * Dossier du code compilé.
 */
dir: string, 
/**
 * Le dossier et son script de mise à jour existent toujours.
 */
ready: boolean, 
/**
 * Modules de cette version absents de la version officielle proposée (`None` : inconnu).
 */
customModules: Array<string> | null, };
