// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce qu'une texture habille : un objet, un bloc ou l'icône du mod.
 */
export type TextureTarget = { "kind": "item", id: string, } | { "kind": "block", id: string, } | { "kind": "icon" };
