// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetKind } from "./AssetKind";
import type { BlockLayout } from "./BlockLayout";
import type { TextureTarget } from "./TextureTarget";

/**
 * Une texture du projet (existante ou attendue par un objet / bloc déclaré).
 */
export type TextureInfo = { target: TextureTarget, 
/**
 * Nom affiché (traduction du jeu si elle existe).
 */
label: string, 
/**
 * Chemin absolu du PNG.
 */
path: string, 
/**
 * Chemin relatif au projet.
 */
relative: string, exists: boolean, width: number, height: number, 
/**
 * Date de modification (ms), pour rafraîchir l'aperçu.
 */
modified: number | null, 
/**
 * Blocs : répartition des textures sur les faces.
 */
layout: BlockLayout | null, 
/**
 * PNG qu'aucun modèle, objet ni bloc n'utilise (face laissée par un changement de
 * répartition, fichier en trop) : proposé à la suppression.
 */
unused: boolean, 
/**
 * Textures libres : leur famille.
 */
assetKind: AssetKind | null, 
/**
 * Fichier du mod qui cite la texture (code, modèle, JSON), quand il est connu.
 */
usedBy: string | null, };
