// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockFace } from "./BlockFace";

/**
 * Ce qu'une texture habille : un objet, un bloc (ou une de ses faces), l'icône du mod, un
 * élément d'interface (`textures/gui/`) ou toute autre texture du mod (superposition,
 * entité, armure, particule…).
 */
export type TextureTarget = { "kind": "item", id: string, } | { "kind": "block", id: string, 
/**
 * `None` : la texture unique du bloc (`cube_all`).
 */
face: BlockFace | null, } | { "kind": "icon" } | { "kind": "gui", name: string, } | { "kind": "asset", path: string, };
