// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Style demandé au modèle d'image.
 */
export type TextureStyle = "vanilla" | "detailed" | "simple";
