// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PixelOptions } from "./PixelOptions";
import type { TextureTarget } from "./TextureTarget";

export type TextureRequest = { target: TextureTarget, 
/**
 * Ce que la personne décrit (« épée en rubis, garde dorée »).
 */
description: string, model: string, options: PixelOptions, 
/**
 * Accord explicite pour un modèle payant.
 */
allowPaid: boolean, };
