// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageProvider } from "./ImageProvider";
import type { PixelOptions } from "./PixelOptions";
import type { PromptSettings } from "./PromptSettings";
import type { TextureTarget } from "./TextureTarget";

export type TextureRequest = { target: TextureTarget, 
/**
 * Ce que la personne décrit (« épée en rubis, garde dorée »).
 */
description: string, 
/**
 * Service qui dessine (OpenRouter si absent : demandes d'avant Gemini).
 */
provider: ImageProvider, model: string, options: PixelOptions, 
/**
 * Accord explicite pour un modèle payant.
 */
allowPaid: boolean, prompt: PromptSettings, 
/**
 * Texte envoyé tel quel au modèle, à la place du texte construit.
 */
customPrompt: string | null, 
/**
 * Texture du projet envoyée en référence (chemin relatif au projet, `.png`).
 */
reference: string | null, };
