// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftSource } from "./DraftSource";
import type { PixelOptions } from "./PixelOptions";
import type { TextureTarget } from "./TextureTarget";

/**
 * Texture proposée, pas encore écrite dans le projet.
 */
export type TextureDraft = { id: string, projectId: string, target: TextureTarget, source: DraftSource, 
/**
 * Image reçue ou importée, telle quelle.
 */
originalPath: string, originalWidth: number, originalHeight: number, 
/**
 * Texture convertie (PNG), réécrite à chaque réglage.
 */
pixelPath: string, options: PixelOptions, 
/**
 * Augmente à chaque conversion : contourne le cache de l'aperçu.
 */
revision: number, createdAt: string, 
/**
 * Retouchée à la main : une nouvelle conversion effacerait ces retouches.
 */
edited: boolean, 
/**
 * Qualité du raccord quand la texture est répétée (0 à 100), textures pleines seulement.
 */
seam: number | null, 
/**
 * Ce que la conversion a corrigé (cadre retiré, raccord…).
 */
notes: Array<string>, };
