// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Raccord d'une texture répétée côte à côte.
 */
export type Tiling = "none" | "horizontal" | "both";
