// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateEvent = { "type": "downloading", received: number, total: number, } | { "type": "verifying" } | { "type": "installing" };
