// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailableUpdate } from "./AvailableUpdate";
import type { InstallKind } from "./InstallKind";
import type { SourceBuild } from "./SourceBuild";

export type UpdateStatus = { current: string, kind: InstallKind, 
/**
 * Compilée depuis le code source (et non publiée) : mise à jour par recompilation.
 */
source: SourceBuild | null, 
/**
 * `None` : ARCHIMED est à jour (ou build de développement).
 */
available: AvailableUpdate | null, 
/**
 * Page des releases, pour télécharger à la main.
 */
releasesUrl: string, };
