// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * Problème trouvé sans compiler : fichier illisible, référence cassée, format d'une autre version.
 */
export type ValidationIssue = { severity: Severity, 
/**
 * Chemin relatif au projet, avec des `/`.
 */
file: string, line: number | null, column: number | null, message: string, hint: string | null, };
