// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileInfo } from "./ProfileInfo";
import type { VersionOption } from "./VersionOption";

/**
 * Versions de Minecraft connues des loaders, croisées avec les profils.
 */
export type VersionCatalog = { versions: Array<VersionOption>, profiles: Array<ProfileInfo>, 
/**
 * Au moins une source n'a pas répondu : données issues du cache.
 */
offline: boolean, 
/**
 * Sources injoignables et sans cache (message lisible).
 */
errors: Array<string>, };
