// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionChoice } from "./VersionChoice";

/**
 * Versions disponibles pour un couple Minecraft × loader, les plus récentes d'abord.
 */
export type VersionOptions = { loader: Array<VersionChoice>, 
/**
 * Yarn (Fabric) ; vide pour les mappings officiels.
 */
mappings: Array<VersionChoice>, 
/**
 * Fabric API ; vide pour Forge et NeoForge.
 */
api: Array<VersionChoice>, offline: boolean, };
