// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderSupport } from "./LoaderSupport";

export type VersionOption = { minecraft: string, loaders: Array<LoaderSupport>, };
