// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une version proposée dans une liste (loader, mappings, API).
 */
export type VersionChoice = { value: string, 
/**
 * Stable (par opposition à bêta) selon la source officielle.
 */
stable: boolean, 
/**
 * Version recommandée par le loader (Forge) ou la plus récente stable.
 */
recommended: boolean, };
