// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Versions choisies à la main ; `None` = celle proposée par défaut.
 */
export type VersionSelection = { loaderVersion: string | null, mappingsVersion: string | null, apiVersion: string | null, };
