// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fournisseur en ligne (ou serveur local compatible) et état de sa clé.
 */
export type VoiceProviderStatus = { id: string, name: string, hasKey: boolean, 
/**
 * Début et fin de la clé, jamais la clé entière.
 */
masked: string | null, needsKey: boolean, };
