// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VoiceModelStatus = "notInstalled" | "downloading" | "paused" | "verifying" | "installing" | "installed" | "updateAvailable" | "failed";
