// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Avancement d'une installation (événement `voice:install`).
 */
export type VoiceInstallProgress = { id: string, step: string, received: number, total: number, };
