// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Convenance d'un modèle pour la machine.
 */
export type VoiceModelFit = "recommended" | "optional" | "notRecommended" | "unsupported";
