// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une voix proposée par un moteur.
 */
export type VoiceOption = { id: string, name: string, language: string | null, 
/**
 * Profil personnalisé (voix clonée avec consentement, gérée par le moteur).
 */
custom: boolean, };
