// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outil local proposé par la voix (Ollama, Voicebox) et ce qu'on peut en faire d'un clic.
 */
export type VoiceToolStatus = { id: string, name: string, installed: boolean, running: boolean, 
/**
 * Installation en un clic possible sur ce système (winget, release vérifiée).
 */
canInstall: boolean, 
/**
 * Installé et lançable depuis ARCHIMED.
 */
canLaunch: boolean, 
/**
 * Page officielle de téléchargement.
 */
page: string, };
