// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceModelStatus } from "./VoiceModelStatus";

/**
 * Avancement d'un téléchargement (événement `voice:model`).
 */
export type VoiceModelProgress = { id: string, status: VoiceModelStatus, received: number, total: number, 
/**
 * Étape en cours (« Téléchargement de l'outil whisper.cpp »…).
 */
step: string | null, error: string | null, };
