// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Résumé d'une session vocale enregistrée.
 */
export type VoiceSessionSummary = { id: string, title: string, startedAt: number, updatedAt: number, turns: number, };
