// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceModelFit } from "./VoiceModelFit";
import type { VoiceModelKind } from "./VoiceModelKind";
import type { VoiceModelStatus } from "./VoiceModelStatus";

/**
 * Un modèle du catalogue, avec son état sur cette machine.
 */
export type VoiceModelEntry = { id: string, kind: VoiceModelKind, name: string, description: string, 
/**
 * Moteur qui l'utilise : `whisper.cpp`, `piper`, `ollama`.
 */
engine: string, version: string, sizeMb: number, ramMb: number, vramMb: number | null, 
/**
 * 1 (lent) à 5 (instantané).
 */
speed: number, 
/**
 * 1 (basique) à 5 (excellente).
 */
quality: number, languages: Array<string>, capabilities: Array<string>, license: string, fit: VoiceModelFit, status: VoiceModelStatus, 
/**
 * Outil local nécessaire (`runtime-whisper`, `runtime-piper`) ou `ollama`.
 */
requires: string | null, received: number, total: number, error: string | null, 
/**
 * Dossier d'installation, quand le modèle est installé.
 */
path: string | null, };
