// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeKind } from "./ChangeKind";

/**
 * Fichier que l'agent a créé, modifié ou supprimé dans sa copie.
 */
export type WorkChange = { path: string, kind: ChangeKind, 
/**
 * Le fichier du projet a aussi changé depuis la copie : appliquer écraserait ce changement.
 */
conflict: boolean, binary: boolean, 
/**
 * Texte actuel dans le projet (`null` : absent, binaire ou trop gros).
 */
before: string | null, 
/**
 * Texte proposé par l'agent.
 */
after: string | null, 
/**
 * Chemin absolu de la version de l'agent (aperçu d'image).
 */
workPath: string, };
