// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Copie de travail de l'agent (son dossier de travail).
 */
export type WorkInfo = { 
/**
 * Chemin absolu : `cwd` de la conversation.
 */
path: string, files: number, 
/**
 * Modifications de l'agent pas encore appliquées ni rejetées.
 */
pending: number, };
