plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '{{plugin_version}}'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    sourceCompatibility = JavaVersion.VERSION_{{java_version}}
    targetCompatibility = JavaVersion.VERSION_{{java_version}}
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            args '--nogui'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    // Add repositories for third-party dependencies here.
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = {{java_version}}
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title'     : mod_id,
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion
        ])
    }
    finalizedBy 'reobfJar'
}
