plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '{{plugin_version}}'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    sourceCompatibility = JavaVersion.VERSION_{{java_version}}
    targetCompatibility = JavaVersion.VERSION_{{java_version}}
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    // Add repositories for third-party dependencies here.
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = {{java_version}}
}
